version: '3'

services:
    mysql:
        build: docker/mysql
        container_name: mysql
        ports:
            - 33060:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=symfony
            - MYSQL_PASSWORD=symfony
            - MYSQL_DATABASE=symfony
        volumes:
            - ./var/db:/var/lib/mysql
    symfony:
        build: docker/symfony
        container_name: symfony
        working_dir: /var/www
        links:
            - mysql
        ports:
            - 8000:80
        volumes:
            - .:/var/www
