# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
    build:
        docker:
            # Specify the version you desire here
            - image: circleci/php:7.3-node-browsers
            - image: circleci/mysql:5.7.26

        # Set working directory
        working_directory: ~/repo

        steps:
            - checkout

            # Install PHP extensions
            - run:
                  name: Install PHP extensions
                  command: sudo docker-php-ext-install iconv pdo_mysql

            # Download and cache Composer dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-composer-dependencies-{{ checksum "composer.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-composer-dependencies-

            # Download and cache NPM dependencies
            - restore_cache:
                  keys:
                      - v1-npm-dependencies-{{ checksum "yarn.lock" }}
                      - v1-npm-dependencies-

            # Download and cache PHPUnit dependencies
            - restore_cache:
                  keys:
                      - v1-phpunit-dependencies-{{ checksum "bin/.phpunit/phpunit-6.5/composer.lock" }}
                      - v1-phpunit-dependencies-

            # Setup Composer locally
            - run:
                  name: Download Composer
                  command: wget https://getcomposer.org/composer.phar; chmod 0700 ./composer.phar

            # Install dependencies via installed Composer
            - run:
                  name: Install Composer dependencies
                  command: ./composer.phar install -n --prefer-dist

            # Cache Composer dependencies
            - save_cache:
                  key: v1-composer-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor

            # Cache NPM dependencies
            - save_cache:
                  key: v1-npm-dependencies-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules

            - run:
                  name: Generate private key
                  command: |
                      openssl genrsa -out private.key 2048 && \
                      echo "OAUTH2_PRIVATE_KEY=/home/circleci/repo/private.key" >> .env.test.local

            - run:
                  name: Generate public key
                  command: |
                      openssl rsa -in private.key -pubout -out public.key && \
                      echo "OAUTH2_PUBLIC_KEY=/home/circleci/repo/public.key" >> .env.test.local

            - run:
                  name: Generate encryption key
                  command: |
                      php -r 'echo base64_encode(random_bytes(32)), PHP_EOL;' >> encryption.key && \
                      echo "OAUTH2_ENCRYPTION_KEY=/home/circleci/repo/encryption.key" >> .env.test.local

            # Migrate database
            - run:
                  name: Migrate database
                  command: ./bin/console doctrine:migrations:migrate -n

            # Run tests with phpunit
            - run:
                  name: Run PHPUnit
                  command: ./bin/phpunit

            # Cache PHPUnit dependencies
            - save_cache:
                  key: v1-phpunit-dependencies-{{ checksum "bin/.phpunit/phpunit-6.5/composer.lock" }}
                  paths:
                      - ./bin/.phpunit
